In [1]:
# Install pandas into the current Python environment (run this cell once), then import it
import sys, subprocess
subprocess.check_call([sys.executable, "-m", "pip", "install", "--upgrade", "pip"])
subprocess.check_call([sys.executable, "-m", "pip", "install", "pandas"])
import pandas as pd
subprocess.check_call([sys.executable, "-m", "pip", "install", "matplotlib", "datasets"])
import matplotlib.pyplot as plt
from datasets import load_dataset
import sys, subprocess
dataset = load_dataset("lukebarousse/data_jobs")
df = dataset["train"].to_pandas()
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

c:\Users\Admin\anaconda3\envs\python_data\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [18]:
df_salary = df[pd.notna(df['salary_year_avg'])]

In [20]:
def projected_salary(salary):
    return salary * 1.03
df_salary['inflated_salary'] = df_salary['salary_year_avg'].apply(projected_salary)

In [21]:
df_salary[['inflated_salary','salary_year_avg']]

        inflated_salary  salary_year_avg
28            112785.00         109500.0
77            144200.00         140000.0
92            123600.00         120000.0
100           235068.66         228222.0
109            91670.00          89000.0
...                 ...              ...
785624        143392.48         139216.0
785641        154500.00         150000.0
785648        228531.25         221875.0
785682        162225.00         157500.0
785692        162225.00         157500.0

[22003 rows x 2 columns]

In [10]:
df['job_posted_date_str'] = df['job_posted_date'].apply(lambda x: x.strftime('%Y-%m-%d') )
df[['job_posted_date', 'job_posted_date_str']]

           job_posted_date job_posted_date_str
0      2023-06-16 13:44:15          2023-06-16
1      2023-01-14 13:18:07          2023-01-14
2      2023-10-10 13:14:55          2023-10-10
3      2023-07-04 13:01:41          2023-07-04
4      2023-08-07 14:29:36          2023-08-07
...                    ...                 ...
785736 2023-03-13 06:16:16          2023-03-13
785737 2023-03-12 06:18:18          2023-03-12
785738 2023-03-12 06:32:36          2023-03-12
785739 2023-03-12 06:32:15          2023-03-12
785740 2023-03-13 06:16:31          2023-03-13

[785741 rows x 2 columns]

In [12]:
df_filtered = df.dropna(subset=['salary_year_avg']).copy()
df_filtered['salary_category'] = df['salary_year_avg'].apply(lambda salary: 'Low' if salary < 60000 else 'Medium' if salary <= 100000 else 'High')
df_filtered[['salary_year_avg', 'salary_category']].reset_index()

        index  salary_year_avg salary_category
0          28         109500.0            High
1          77         140000.0            High
2          92         120000.0            High
3         100         228222.0            High
4         109          89000.0          Medium
...       ...              ...             ...
21998  785624         139216.0            High
21999  785641         150000.0            High
22000  785648         221875.0            High
22001  785682         157500.0            High
22002  785692         157500.0            High

[22003 rows x 3 columns]