In [1]:
# Install pandas into the current Python environment (run this cell once), then import it
import sys, subprocess
subprocess.check_call([sys.executable, "-m", "pip", "install", "--upgrade", "pip"])
subprocess.check_call([sys.executable, "-m", "pip", "install", "pandas"])
import pandas as pd
subprocess.check_call([sys.executable, "-m", "pip", "install", "matplotlib", "datasets"])
import matplotlib.pyplot as plt
from datasets import load_dataset
import sys, subprocess
dataset = load_dataset("lukebarousse/data_jobs")
df = dataset["train"].to_pandas()
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

c:\Users\Admin\anaconda3\envs\python_data\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [2]:
df.loc[:10, 'salary_rate':'salary_hour_avg']

   salary_rate  salary_year_avg  salary_hour_avg
0          NaN              NaN              NaN
1          NaN              NaN              NaN
2          NaN              NaN              NaN
3          NaN              NaN              NaN
4          NaN              NaN              NaN
5          NaN              NaN              NaN
6          NaN              NaN              NaN
7          NaN              NaN              NaN
8          NaN              NaN              NaN
9          NaN              NaN              NaN
10         NaN              NaN              NaN

In [6]:
median_year_avg = df['salary_year_avg'].median()

In [7]:
median_hour_avg =df['salary_hour_avg'].median()

In [12]:
data_filled.loc[:10, 'salary_year_avg':'salary_hour_avg']

    salary_year_avg  salary_hour_avg
0          115000.0            45.98
1          115000.0            45.98
2          115000.0            45.98
3          115000.0            45.98
4          115000.0            45.98
5          115000.0            45.98
6          115000.0            45.98
7          115000.0            45.98
8          115000.0            45.98
9          115000.0            45.98
10         115000.0            45.98

In [15]:
df_unique = data_filled 
df_unique = df_unique.drop_duplicates()

In [18]:
df_unique = df.drop_duplicates(subset=['job_title', 'company_name'])

In [23]:
df.loc[5:9,'job_title':'job_posted_date']

,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date
5,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59
6,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18
7,Data Engineer,Anywhere,via LinkedIn,Full-time,True,Romania,2023-12-07 13:40:49
8,Technology & Operations Business Analyst,"Copenhagen, Denmark",via Trabajo.org,Full-time,False,Denmark,2023-06-05 13:44:34
9,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57

In [ ]:
df_us = df[df['job_country'] == 'United States']
df_us[['job_title', 'salary_year_avg']].iloc[:15]

                                            job_title  salary_year_avg
0   Senior Clinical Data Engineer / Principal Clin...         115000.0
3   LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...         115000.0
5                                   GCP Data Engineer         115000.0
6                   Senior Data Engineer  - GCP Cloud         115000.0
9                                   Data Scientist II         115000.0
11                                      Data Engineer         115000.0
13                               Senior Data Engineer         115000.0
17                             Data Science Team Lead         115000.0
26                                      Data Engineer         115000.0
27  Principal Data Engineer (Lead), Knowledge Grap...         115000.0
30     Senior Data Engineer (Work from home Eligible)         115000.0
32   Sr. Data Scientist (NLP) - Full-time / Part-time         115000.0
35                        Data Engineer - Royal Canin         115000.0
36                                       Data Analyst         115000.0
37                     Data Engineer III - Now Hiring         115000.0

In [36]:
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [37]:
df.loc[df['job_posted_date'] > '2023-05-01', ['job_title', 'job_location', 'job_posted_date']]

,job_title,job_location,job_posted_date
0,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",2023-06-16 13:44:15
2,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",2023-10-10 13:14:55
3,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",2023-07-04 13:01:41
4,Data Engineer- Sr Jobs,"Washington, DC",2023-08-07 14:29:36
5,GCP Data Engineer,Anywhere,2023-11-07 14:01:59
...,...,...,...
785694,Data Engineer,"Graz, Austria",2023-05-07 07:07:37
785696,Senior Analytics Engineer,"Colombia, Huila, Colombia",2023-10-23 06:31:25
785698,"Data Engineer, Gerencia Business Intelligence","Las Condes, Chile",2023-08-09 06:32:00
785701,"Data Engineer, Gerencia Business Intelligence","Santiago, Chile",2023-08-09 06:31:57
785706,Junior Data Engineer,"Lima, Peru",2023-11-08 06:34:48

In [45]:
rows_before = len(df)

df_cleaned = df.dropna(subset=['salary_year_avg'])
rows_after = len(df_cleaned)

rows_before, rows_after

(785741, 785741)

In [52]:
print(df['salary_rate'].iloc[:11])
df['fillrate'] = df['salary_rate'].fillna('unknown')
print(df['fillrate'].iloc[:11])

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
5     NaN
6     NaN
7     NaN
8     NaN
9     NaN
10    NaN
Name: salary_rate, dtype: str
0     unknown
1     unknown
2     unknown
3     unknown
4     unknown
5     unknown
6     unknown
7     unknown
8     unknown
9     unknown
10    unknown
Name: fillrate, dtype: str